export const TOGGLE_MENU_HANDLER = 'MENU/TOGGLE_MENU_HANDLER';
export const MENU_CLOSE_HANDLER = 'MENU/MENU_CLOSE_HANDLER';

export const FETCH_PRODUCTS_DATA_START = 'FETCH_PRODUCTS_DATA_START';
export const FETCH_PRODUCTS_DATA_SUCCESS = 'FETCH_PRODUCTS_DATA_SUCCESS';
export const FETCH_PRODUCTS_DATA_ERROR = 'FETCH_PRODUCTS_DATA_ERROR';

export const FETCH_CUSTOMERS_DATA_SUCCESS = 'FETCH_CUSTOMERS_DATA_SUCCESS';
export const FETCH_CUSTOMERS_DATA_ERROR = 'FETCH_CUSTOMERS_DATA_ERROR';

export const ADD_NEW_CUSTOMER = 'REGISTR/ADD_NEW_CUSTOMER';

export const HAS_ACCOUNT = 'AUTH/HAS_ACCOUNT';
export const CUSTOMER_NEXT_ID = 'AUTH/CUSTOMER_NEXT_ID';
export const AUTH_SUCCESS = 'AUTH/AUTH_SUCCESS';
export const AUTH_SUCCESS_ADMIN = 'AUTH/AUTH_SUCCESS_ADMIN';
export const AUTH_LOGOUT = 'AUTH/AUTH_LOGOUT';
export const AUTH_LOGOUT_ADMIN = 'AUTH/AUTH_LOGOUT_ADMIN';

export const TOGGLE_FILTER_HANDLER = 'FILTER/TOGGLE_FILTER_HANDLER';
export const ON_SELECTED_PRODUCTS = 'FILTER/ON_SELECTED_PRODUCTS';
export const ON_SELECTED_PRODUCTS_ADMIN = 'FILTER/ON_SELECTED_PRODUCTS_ADMIN';
export const RESET_FILTERS = 'FILTER/RESET_FILTERS';
export const RESET_FILTERS_ADMIN = 'FILTER/RESET_FILTERS_ADMIN';
export const UPDATE_FILTER_PROPS = 'FILTER/UPDATE_FILTER_PROPS';
export const UPDATE_FILTER_PROPS_ADMIN = 'FILTER/UPDATE_FILTER_PROPS_ADMIN';
export const SET_FILTER_BY = 'FILTER/SET_FILTER_BY';
export const SET_SEARCH_QUERY = 'FILTER/SET_SEARCH_QUERY';

export const UPDATE_IS_SUBCATEGORY = 'PRODUCTCREATOR/UPDATE_IS_SUBCATEGORY';
export const UPDATEPRODUCTS = 'PRODUCTCREATOR/UPDATEPRODUCTS';
export const UPDATE_PRODUCTS_DELETED = 'PRODUCTCREATOR/UPDATE_PRODUCTS_DELETED';
export const UPDATECATEGORIES = 'PRODUCTCREATOR/UPDATECATEGORIES';

export const UPDATE_ORDERS = 'PRODUCT/UPDATE_ORDERS';
export const UPDATE_ORDERS_HISTORY = 'PRODUCT/UPDATE_ORDERS_HISTORY';
export const UPDATE_IS_ORDERS_THIS_CART = 'PRODUCT/UPDATE_IS_ORDERS_THIS_CART';
export const UPDATE_IS_ORDERS_HISTORY_THIS_CART = 'PRODUCT/UPDATE_IS_ORDERS_HISTORY_THIS_CART';
export const UPDATE_IS_QUANT_PROD_IN_DB = 'PRODUCT/UPDATE_IS_QUANT_PROD_IN_DB';
export const SET_CURRENT_PAGE = 'PAGINATION/SET_CURRENT_PAGE';
export const SET_TOTAL_PRODUCTS_COUNT = 'PAGINATION/SET_TOTAL_PRODUCTS_COUNT';
export const CHANGE_PORTION_NUMBER = 'PAGINATION/CHANGE_PORTION_NUMBER';
export const UPDATE_CUSTOMERS = 'CUSTOMERS/UPDATE_CUSTOMERS';
export const UPDATE_CUSTOMER_NAME = 'CUSTOMERS/UPDATE_CUSTOMER_NAME';
export const UPDATE_CUSTOMER_ID = 'CUSTOMERS/UPDATE_CUSTOMER_ID';
export const UPDATE_ID_LAST_CUSTOMER = 'CUSTOMERS/UPDATE_ID_LAST_CUSTOMER';
export const FETCH_DATE_OF_FIRST_VISIT_NEW_CUSTOMER = 'CUSTOMERS/FETCH_DATE_OF_FIRST_VISIT_NEW_CUSTOMER';
export const FETCH_QUANTITY_VISITORS = 'CUSTOMERS/FETCH_QUANTITY_VISITORS';
export const FETCH_QUANTITY_OF_DOWNLOADS = 'CUSTOMERS/FETCH_QUANTITY_OF_DOWNLOADS';

export const TOGGLE = 'CUSTOMERS_TABLE/TOGGLE';
export const TOGGLE_ALL_CUSTOMERS = 'CUSTOMERS_TABLE/TOGGLE_ALL_CUSTOMERS';
